spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instadb?serverTimezone=Asia/Seoul
    username: jihwan
    password: ENC(fZCdT3wgQWhqylrNxoG63OrUf6PM0ZbFIwB3xO3Z0hx2bDXhI4LMyj6NowfS/hVm)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ENC(no1gfK9aqp/WjBLQ7fJ48orCph+ZvIjJvZWGVAml5aJGWkZZJTFwtyoqMD+Efe80Fth2IqljbhUCPSmPNNEt0w==)
      secret-key: ENC(7jieq6Q0EJBclEMmyywKn0dFRL7VWZI7YeTXTsb3mg8EATkf5FIXGTBYccyXY/SFaH/zECDWFqN4kyW8dS5CgKW9QFWl/tkpUAVC5eCI+8w=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: numble-insta-bucket

jwt:
  token:
    header: Authorization
    issuer: numblejihwan
    client-secret: ENC(4z4+L0WVk8v4BgKGW+By9EK5g7J659t0Hb43rl804bKmgowzNvHcPI04QApzX+PQ)
    expirySeconds: 60
